blog_list:
    path: /test
    controller: App\Controller\LuckyController::showJson
    methods: GET

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

